apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - overlays/production/argo-cd-ui-ingress.yaml
  #- https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.2/manifests/ha/install.yaml
  - base/install.yaml
  - overlays/production/tls.yaml
  - applications.yaml
  - repositories.yaml
  - projects.yaml
  - clusters.yaml



patchesStrategicMerge:
  - overlays/production/argocd-cm.yaml
  - overlays/production/argocd-notifications-cm.yaml
  - overlays/production/argocd-notifications-timezone.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        policy.default: role:readonly
        policy.csv: |
          p, role:pre-admin, applications, *, default/*, allow
          g, pre-admin, role:pre-admin
    target:
      labelSelector: "app.kubernetes.io/name=argocd-rbac-cm"

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: "--insecure"
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=argocd-server

namespace: argocd

